---
# tasks file for asgspot
# You must be sure at least one spotinst in ASG exist
#
- name: "Copy script to add spotinst to ASG"
  copy:
     src: "{{role_path}}/files/addinstance.sh"
     dest: "/usr/local/bin/addinstance.sh"
     mode: 0644
     owner: ubuntu
     group: ubuntu
  become: true
  become_user: root

- name: "Copy script to drop out spotinst from ASG"
  copy:
     src: "{{role_path}}/files/dropinstance.sh"
     dest: "/usr/local/bin/dropinstance.sh"
     mode: 0644
     owner: ubuntu
     group: ubuntu
  become: true
  become_user: root

- name: "Copy script to add/del backends to/from  /etc/pgpool/pgpool.conf"
  copy:
     src: "{{role_path}}/files/pgconfi.php"
     dest: "/usr/local/bin/pgconfi.php"
     mode: 0750
     owner: root
     group: root
  become: true
  become_user: root

- name: "Copy rsspot service to systemd"
  copy:
     src: "{{role_path}}/files/rsspot.service"
     dest: "/lib/systemd/system/rsspot.service"
     mode: 0644
     owner: root
     group: root
  become: true
  become_user: root

- name: "Enable rsspot service on reboot"    
  systemd:
    name: rsspot.service
    state: started
    enabled: yes
    daemon_reload: yes
  become: true
  become_user: root
...
