---
- name: "Stop PostgreSQL instances"
  hosts: db
  gather_facts: true
  vars_files:
    - creds.yml
  tasks:
    - name: "Display PostgreSQL nodes" 
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"
   
    - name: "Stop PosgreSQL service"    
      systemd:
        name: postgresql@9.6-main.service
        state: stopped
      become: true
      become_user: root

    - name: "Stop repmgrd service"
      systemd:
        name: repmgrd.service
        state: stopped
      become: true
      become_user: root
...

