---
- name: "Start PostgreSQL instances"
  hosts: db
  gather_facts: true
  vars_files:
    - creds.yml
  tasks:
    - name: "Display PostgreSQL nodes" 
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"
   
    - name: "Start PostgreSQL service"    
      systemd:
        name: postgresql@9.6-main.service
        state: started
      become: true
      become_user: root
    
    - name: "Start repmgrd service"    
      systemd:
        name: repmgrd.service
        state: started
      become: true
      become_user: root

...

