---
- name: "Stop PostgreSQL instances"
  hosts: db
  gather_facts: true
  vars_files:
    - creds.yml
  tasks:
    - name: "Display PostgreSQL nodes" 
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"
   
    - name: "Stop PosgreSQL instances"    
      systemd:
        state: started
        name: postgresql@9.6-main.service
      become: true
      become_user: root

...

