---
- name: "Tuning PostgreSQL replication"
  hosts: db
  gather_facts: true
  vars_files:
    - creds.yml
  tasks:
    - name: Display Postgresql hostnames 
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"
  roles:
    - common
    - role: postgres
      vars:
        master_hostname: ip-172-31-33-42
#- name: "Tuning PGPool with watchdog"
#  hosts: pgpnodes
#  gather_facts: true
#  vars_files:
#    - creds.yml
#  tasks:
#    - name: Display PGPool hostnames 
#      debug:
#        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"
#  roles:
#    - pgpool
...

