---
# defaults file for pgpool
pguser: postgres
pggroup: postgres
pgpool_users: pgpooler
pg_ver: 9.6
pgdata: /var/lib/postgresql/9.6/main
pghome: /var/lib/posgresql
pgpuser: pgpooler
aws_region: eu-west-1
aws_output_format: json
vip_address: 34.253.86.163
home: /home/ubuntu
