---
# tasks file for common

- name: "Update /etc/hosts file"
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'hosts.j2') }}"
    state: present
  become: yes
  become_user: root
  tags: common

- name: Change ssh_config parameter StrictHostKeyChecking to no
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^StrictHostKeyChecking'
    line: 'StrictHostKeyChecking = no'
    state: present
  become: yes
  become_user: root
  tags: common

- name: Fix for locales
  lineinfile:
    path: /etc/environment
    line: "export LC_ALL=en_US.UTF-8" 
    create: yes
  become: yes
  become_user: root
  tags: common

- name: "Add Ubuntu postgres repo"
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'
    filename: 'pgdg'
  become: yes
  become_user: root
  tags: common

- name: "Add an Apt signing key"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes
  become_user: root
  tags: common

- name: "Install system packages"
  apt:
    name: "{{ packages }}"
    force_apt_get: true
  vars:
    packages:
    - nmap
    - curl
    - wget
    - nmon
    - strace
    - ca-certificates
    - ec2-api-tools
    - awscli
  become: true
  become_user: root
  tags: common

- sysctl:
    name: net.core.somaxconn
    value: '256'
    state: present
  become: true
  become_user: root
  tags: common

- sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present
  become: true
  become_user: root
  tags: common

- sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
  become: true
  become_user: root
  tags: common

- sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    state: present
  become: true
  become_user: root
  tags: common

- name: cross-authorize private SSH key access from this VM to other VMs
  copy:
     src: /home/ubuntu/.ssh/id_rsa
     dest: /home/ubuntu/.ssh/id_rsa
     mode: 0400
     owner: ubuntu
     group: ubuntu
  become: true
  become_user: root
  tags: common

- name: cross-authorize public SSH key access from this VM to other VMs
  copy:
     src: /home/ubuntu/.ssh/id_rsa
     dest: /home/ubuntu/.ssh/id_rsa
     mode: 0400
     owner: ubuntu
     group: ubuntu
     backup: yes
  become: true
  become_user: root
  tags: common

- name: Set authorized key taken from file
  authorized_key:
    user: ubuntu 
    state: present
    key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
  delegate_to: localhost
  become: true
  become_user: root
  tags: common

  #- name: "Disable AWS Cloud network settings"
  #copy: 
  #  src: "{{ role_path }}/files/99-disable-network-config.cfg"
  #  dest: "/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"
  #  force: no
  #  mode: 0644
  #become: true
  #become_user: root

  
  #- name: "Change AWS Cloud network settings"
  #template: 
  #  src: interfaces.j2 
  #  dest: "/etc/network/interfaces"
  #  force: yes
  #  mode: 0644
  #become: true
  #become_user: root
  #notify:
  #  - restart network

  #- name: "Restart the network if handler will not restart"
  #systemd:
  #  name: networking
  #  state: restarted
  #become: true
  #become_user: root
...

