---
# tasks file for common

- name: "Update /etc/hosts file"
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'hosts.j2') }}"
    state: present
  become: yes
  become_user: root
  tags: common

- name: Change ssh_config parameter StrictHostKeyChecking to no
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^StrictHostKeyChecking'
    line: 'StrictHostKeyChecking = no'
    state: present
  become: yes
  become_user: root
  tags: common

- sysctl:
    name: net.core.somaxconn
    value: '256'
    state: present
  become: true
  become_user: root

- sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present
  become: true
  become_user: root

- sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
  become: true
  become_user: root

- sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    state: present
  become: true
  become_user: root

  #- name: "Disable AWS Cloud network settings"
  #copy: 
  #  src: "{{ role_path }}/files/99-disable-network-config.cfg"
  #  dest: "/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"
  #  force: no
  #  mode: 0644
  #become: true
  #become_user: root

  
  #- name: "Change AWS Cloud network settings"
  #template: 
  #  src: interfaces.j2 
  #  dest: "/etc/network/interfaces"
  #  force: yes
  #  mode: 0644
  #become: true
  #become_user: root
  #notify:
  #  - restart network

  #- name: "Restart the network if handler will not restart"
  #systemd:
  #  name: networking
  #  state: restarted
  #become: true
  #become_user: root
...

